### PR TITLE
add license

### LINKED ISSUE #5: Licensing
Our options for licensing are these(ordered by my liking):
1- CC-BY-SA: https://creativecommons.org/licenses/by-sa/3.0/
2- PDL: https://www.openoffice.org/licenses/PDL.html
3- GFDL: https://www.gnu.org/licenses/fdl-1.3.en.html
4- MIT

### PR DESCRIPTION
**Pull request by AriaMoradi**
closes #5

This is CC-BY-SA

### CODE REVIEW

**Comment by gombosg** [comment]
See: https://github.com/AntiMicroX/antimicrox.github.io/issues/5#issuecomment-737135840

**Comment by AriaMoradi** [comment]
changed to GPL v3

**Review by gombosg — APPROVED** [review]
LGTM, I think you can really merge into this repo. :D

**Comment by AriaMoradi** [comment]
> LGTM, I think you can really merge into this repo. :D

Yeah :rocket:

**Pull request merged**
